# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'precise64'
  config.vm.hostname = 'lab1.local'
  config.vm.network 'forwarded_port', guest: 80, host: 8080
  config.vm.network 'forwarded_port', guest: 8081, host: 8081
  config.vm.network 'forwarded_port', guest: 8082, host: 8082
  config.vm.network 'forwarded_port', guest: 443, host: 8443

  config.vm.box_url = '/stash/nixmentors/boxes/precise64.box'

  config.vm.provision :shell, inline: 'apt-get update'

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file     = 'init.pp'
    puppet.manifests_path    = '../puppet/manifests'
  end

end
