# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# centos64 base box is from https://cat.pdx.edu/~nibz/vagrant/centos-6.4-amd64.box
# but basically any (functional) centos6 box should work
# the centos6 box on vagrantbox.es was broken at time of writing

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
   port = 1
   config.vm.provider :virtualbox do |vb|
     ["b","c","d","e","f","g"].each do |disk|
       diskname = "/disk/trump/minerals/#{ENV['USER']}/sd#{disk}.vdi"
       vb.customize ['createhd', '--filename', diskname, '--size', 1024]
       vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', port, '--device', 0, '--type', 'hdd', '--medium', diskname]
       port += 1
     end
   end


  config.vm.define "linuxfiler" do |v|
    v.vm.box = "precise64"
    v.vm.hostname = "linuxfiler"
    v.vm.network :private_network, ip: "192.168.1.10"
    v.vm.box_url = "/stash/nixmentors/boxes/precise64.box"
  end

end
