# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box_url = "/stash/nixmentors/boxes/precise64.box"


  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.box = "precise64"
    puppetmaster.vm.hostname = "puppetmaster.local"
    puppetmaster.vm.network :private_network, ip: "192.168.1.10"
  end

  config.vm.define "client" do |client|
    client.vm.box = "precise64"
    client.vm.hostname = "client.local"
    client.vm.network :private_network, ip: "192.168.1.11"
  end

end
