# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define 'centos' do |centos|
    centos.vm.box = 'centos64'
    centos.vm.hostname = 'centos'
    centos.vm.network :private_network, ip: '192.168.1.10'
    centos.vm.box_url = '/stash/nixmentors/boxes/centos-6.4-amd64.box'
  end

  config.vm.define 'precise' do |v|
    v.vm.box = 'precise64'
    v.vm.hostname = 'precise64'
    v.vm.network :private_network, ip: '192.168.1.11'
    v.vm.box_url = '/stash/nixmentors/boxes/precise64.box'
  end

  config.vm.define 'solaris' do |v|
    v.vm.box = 'solaris-11.1'
    v.vm.hostname = 'sunosfiler1'
    v.vm.network :private_network, ip: '192.168.1.12'
    v.vm.box_url = '/stash/nixmentors/boxes/packer_solaris-11.1-amd64_virtualbox.box'
  end

end
